-- CreateEnum
CREATE TYPE "ProductCategory" AS ENUM ('MOBILE_PHONES_ACCESSORIES', 'BEAUTY_PERSONAL_CARE', 'FASHION_APPAREL', 'HOME_KITCHEN', 'HEALTH_WELLNESS', 'BABY_KIDS', 'AUTOMOTIVE_ACCESSORIES', 'GAMING_TECH_ACCESSORIES', 'PET_SUPPLIES', 'SMART_HOME_PRODUCTS');

-- AlterTable
ALTER TABLE "Order" ADD COLUMN     "customerAddress" TEXT,
ADD COLUMN     "customerName" TEXT,
ADD COLUMN     "customerPhone" TEXT,
ADD COLUMN     "deliveryFeeInCents" INTEGER NOT NULL DEFAULT 700;

-- AlterTable
ALTER TABLE "Product" ADD COLUMN     "category" "ProductCategory" NOT NULL DEFAULT 'HOME_KITCHEN';
